### ISSUE TITLE
PCB Design Files

### ISSUE THREAD

**Issue by andyolivares** [kriswiner/Firefly#2]
Hi, where can I find the PCB design files? Looking at the images, I assume you used Eagle.
Thank you!

**Comment by kriswiner** [comment]
Linked on the Tindie product page.

**Comment by andyolivares** [comment]
Thanks for the quick reply.
The Tindie product page only links to this OSHPark order site: https://oshpark.com/shared_projects/zXb1DLuA

> What makes it special?
> 
> This is a small, **open-source hardware implementation** designed to make using and customizing the STM32WB55 easy for everyone.

Being this an open-source hardware project, it should be nice to find the actual PCB design files :)

Thank you!

**Comment by kriswiner** [comment]
Download them from the link.

**Comment by andyolivares** [comment]
Didn't notice the files were there in the actions menu. My bad. Thank you.
